name: dnn-project-dev
channels:
- pytorch
dependencies:
- cudatoolkit
- pip
- python=3.8
- pytorch=1.7
- torchvision
- pip:
  - kornia
  - loguru
  - mlconfig
  - mlflow
  - opencv-python
  - pylint
  - pytest
  - tqdm
